# H2
spring.h2.console.enabled: true

# flyway
spring.flyway.baseline-on-migrate: true

# Database
spring.datasource:
  # url: jdbc:h2:mem:db_tool;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE
  url: jdbc:h2:file:~/db_tool;MODE=MYSQL
  driver-class-name: org.h2.Driver
  username: sa
  password: 

logging.level.com.miragesql.miragesql: DEBUG

#devtool
spring.devtools:
  livereload.enabled: true
  restart.enabled: true

#freemarker
spring.freemarker:
  cache: false
  template-loader-path:
    - file:src/main/resources/templates/
    - classpath:/templates/
  settings:
    url_escaping_charset: UTF-8
    number_format: 0.######
    output_format: HTMLOutputFormat
    lazy_auto_imports: true
    auto_import:  "\
      /layout/layout.ftlh as layout,
      /layout/header.ftlh as header,
      /layout/menu.ftlh as menu,
      /layout/footer.ftlh as footer,
      /utils/tag.ftlh as u,
      /utils/spring.ftlh as spring
    "