SELECT 
  FROM_CONSTRAINTS.TABLE_NAME AS from_table_name,
  FROM_CONSTRAINTS.COLUMN_LIST AS from_column_name,
  TO_CONSTRAINTS.TABLE_NAME AS to_table_name,
  TO_CONSTRAINTS.COLUMN_LIST AS to_column_name
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
INNER JOIN INFORMATION_SCHEMA.CONSTRAINTS FROM_CONSTRAINTS ON REFERENTIAL_CONSTRAINTS.CONSTRAINT_NAME = FROM_CONSTRAINTS.CONSTRAINT_NAME
INNER JOIN INFORMATION_SCHEMA.CONSTRAINTS TO_CONSTRAINTS ON REFERENTIAL_CONSTRAINTS.UNIQUE_CONSTRAINT_NAME = TO_CONSTRAINTS.UNIQUE_INDEX_NAME 
  AND TO_CONSTRAINTS.CONSTRAINT_TYPE != 'REFERENTIAL'
WHERE
  FROM_CONSTRAINTS.COLUMN_LIST != TO_CONSTRAINTS.COLUMN_LIST
  AND REFERENTIAL_CONSTRAINTS.CONSTRAINT_CATALOG = /*table_schema*/''
  AND REFERENTIAL_CONSTRAINTS.CONSTRAINT_NAME = /*constraint_name*/''
  AND FROM_CONSTRAINTS.TABLE_NAME = /*from_table_name*/''
  AND FROM_CONSTRAINTS.TABLE_NAME != TO_CONSTRAINTS.TABLE_NAME
GROUP BY from_table_name, from_column_name, to_table_name, to_column_name
ORDER BY REFERENTIAL_CONSTRAINTS.CONSTRAINT_NAME