SELECT 
  REFERENTIAL_CONSTRAINTS.CONSTRAINT_NAME as constraint_name,
  FROM_CONSTRAINTS.TABLE_NAME AS from_table_name,
  TO_CONSTRAINTS.TABLE_NAME AS to_table_name,
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
INNER JOIN INFORMATION_SCHEMA.CONSTRAINTS FROM_CONSTRAINTS ON REFERENTIAL_CONSTRAINTS.CONSTRAINT_NAME = FROM_CONSTRAINTS.CONSTRAINT_NAME
INNER JOIN INFORMATION_SCHEMA.CONSTRAINTS TO_CONSTRAINTS ON REFERENTIAL_CONSTRAINTS.UNIQUE_CONSTRAINT_NAME = TO_CONSTRAINTS.UNIQUE_INDEX_NAME
  AND TO_CONSTRAINTS.CONSTRAINT_TYPE != 'REFERENTIAL'
WHERE
  FROM_CONSTRAINTS.COLUMN_LIST != TO_CONSTRAINTS.COLUMN_LIST
  AND FROM_CONSTRAINTS.TABLE_CATALOG = /*table_schema*/''
  AND FROM_CONSTRAINTS.TABLE_NAME != TO_CONSTRAINTS.TABLE_NAME
GROUP BY constraint_name, from_table_name, to_table_name
ORDER BY REFERENTIAL_CONSTRAINTS.CONSTRAINT_NAME