SELECT
  COLUMNS.TABLE_SCHEMA AS table_schema
  , COLUMNS.TABLE_NAME AS table_name
  , COLUMNS.COLUMN_NAME AS column_name
  , COLUMNS.CHARACTER_MAXIMUM_LENGTH AS character_maximum_length
  , COLUMNS.REMARKS AS column_comment
  , COLUMNS.ORDINAL_POSITION AS ordinal_position
  , COLUMNS.TYPE_NAME AS column_type
  , CASE
    WHEN COLUMNS.NULLABLE = 1 THEN TRUE
    WHEN COLUMNS.NULLABLE = 0 THEN FALSE
    END AS is_nullable
  , COLUMNS.COLUMN_DEFAULT AS column_default
  , CASE
    WHEN CONSTRAINTS.CONSTRAINT_TYPE = 'PRIMARY KEY' THEN 'PRI'
    END AS column_key
  , '' AS extra
FROM INFORMATION_SCHEMA.COLUMNS
LEFT JOIN INFORMATION_SCHEMA.CONSTRAINTS ON CONSTRAINTS.TABLE_CATALOG = COLUMNS.TABLE_CATALOG 
  AND CONSTRAINTS.TABLE_NAME = COLUMNS.TABLE_NAME
  AND CONSTRAINTS.COLUMN_LIST = COLUMNS.COLUMN_NAME 
WHERE
  COLUMNS.TABLE_SCHEMA = 'PUBLIC'
  AND COLUMNS.TABLE_CATALOG = /*table_schema*/'' 
  AND COLUMNS.TABLE_NAME = /*table_name*/''
ORDER BY COLUMNS.TABLE_NAME, COLUMNS.ORDINAL_POSITION